spring:
  application:
    name: distributed-rate-limiter
  data:
    redis:
      host: localhost
      port: 6379
rate-limiter:
  endpoints:
    login:
      limit: 5
      window: 15000
      burst: 0
    otp:
      limit: 2
      window: 60000
      burst: 1